spring.application.name=crave-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/crave_db
spring.datasource.username=postgres
spring.datasource.password=0000
server.port=888
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=kX9pL2mN7qR4tV8wY1zA5bC3dF6gH0jJ3mP8rT2uE5iO9nQ1sW4xZ6
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-part-count=100
server.tomcat.max-part-header-size=2048